services:
  - type: web
    name: frost
    runtime: python
    buildCommand: ""
    startCommand: python server.py
    plan: free
    envVars:
      - key: iNjV/HxQnZt164fCpZsLzno3NWzxyutRknRuWrwhI1E=
        generateValue: true